routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::redirect('/', '/home');
Route::get('/home', 'HomeController@index')->name('home');
Route::prefix('balancedata')->name('balancedata.')->group(function () {
    Route::get('/', 'BalanceDataController@index')->name('index'); // (1)
    Route::post('/create', 'BalanceDataController@create')->name('create'); // (2)
    Route::get('/edit/{id}', 'BalanceDataController@edit')->name('edit'); // (3)
    Route::post('/update/{id}', 'BalanceDataController@update')->name('update'); // (4)
    Route::get('/delete/{id}', 'BalanceDataController@delete')->name('delete'); // (5)
});

app/BalanceData.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class BalanceData extends Model
{
    use SoftDeletes;
    /**
     * このプロパティに設定したフィールドはsaveやupdateメソッドで設定が可能となります。
     *
     * @var array $fillable
     */
    protected $fillable = [
        'occurred_at', 'user_id', 'title', 'type', 'amount', 'description'
    ];

    /**
     * このメソッドでは「Userと１対多」であるというリレーションを設定しています。
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    } //
    /**
     * 収支情報の日付を「yyyy年mm月dd日(w)」形式へ整形して返します。
     *
     * @return String
     */
    public function getOccurredAtFAttribute()
    {
        $date = new Carbon($this->occurred_at);
        $day_of_week = array('日', '月', '火', '水', '木', '金', '土');
        return $date->format('Y年m月d日') . '(' . $day_of_week[$date->format('w')] . ')';
    }

    /**
     * 収支情報の金額を「￥999,999」形式へ整形して返します。
     *
     * @return String
     */
    public function getAmountFAttribute()
    {
        return '￥' . number_format($this->amount) . '';
    }
}

app/Http/Controllers/BalanceDataController.php
<?php

namespace App\Http\Controllers;

use App\BalanceData;
use Collective\Html\FormBuilder;
use Illuminate\Http\Request;
use App\Repositories\BalanceDataRepository;
use App\Http\Requests\BalanceDataRequest;


class BalanceDataController extends Controller
{
    const LIST_ITEM_PER_PAGE = 10;
    protected $balance_data_repository;

    /**
     * 収支情報編集画面用のコントローラークラスのコンストラクタです。
     *
     * @param \App\Repositories\BalanceDataRepository $balance_data_repository
     * DBアクセスを行うリポジトリのインスタンスです。
     * @return void
     */
    public function __construct(BalanceDataRepository $balance_data_repository)
    {
        // ログイン周りのミドルウェアを適用します。
        // このコントローラーにアサインされるルートは全てログインが必須となります。
        $this->middleware('auth');

        // DBアクセスを行うリポジトリのインスタンスをクラス変数に保持します。
        $this->balance_data_repository = $balance_data_repository;

        // 収支情報一覧の各行に配置する操作ボタンの雛形を定義しています。
        FormBuilder::macro('CustomButton', function ($type, $func, $label, $id) {
            return '<button type="button" class="btn btn-sm btn-outline-' . $type
                . '" onclick="' . "balance_data_controller.{$func}('{$id}');"
                . '">' . $label . '</button>';
        });
    }

    /**
     * 収支情報一覧を表示するためのアクションです。
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        // 表示対象年月のパラメータを取得します。
        // パラメータなしの場合は今日の年月を設定します。
        $graph_target_date_info = getYmParam($request, 'ym');
        // 収支情報一覧のデータリストを取得します。
        // 現在のユーザーに紐付く、表示対象年月内のデータを
        // LIST_ITEM_PER_PAGEに指定された件数でページングして取得します。
        $balance_data_list = $this->balance_data_repository->getListData(
            $request->user(),
            $graph_target_date_info['year'],
            $graph_target_date_info['month'],
            self::LIST_ITEM_PER_PAGE
        );
        // 新規登録時用に入力フォーム初期値用に空のモデルをインスタンス化して、
        // 日付入力欄に今日の日付をセットします。
        $balance_data = new BalanceData();
        $balance_data->occurred_at = date('Y-m-d');

        // 収支情報一覧のビューを用意します。
        $renderable = view('balancedata.index');

        // 収支情報一覧で使用する以下のデータをビューに渡します。
        // 1. 収支情報一覧のデータリスト
        // 2. 表示年月パラメータ
        // 3. 入力フォーム初期値用のモデルのインスタンス
        // 4. 入力フォームのaction属性に設定する「新規登録用」のURLを持つrouter
        $renderable->with('balance_data_list', $balance_data_list);
        $renderable->with('ym', getYmString($graph_target_date_info));
        $renderable->with('balance_data', $balance_data);
        $renderable->with('form_router', 'balancedata.create');
        return $renderable;
    }

    /** 入力フォームのデータを受け取り、DBへ保存するためのアクションです。
     *
     * @param \App\Http\Requests\BalanceDataRequest $request
     * バリデーション済みの入力フォームの内容
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function create(BalanceDataRequest $request) {
        // このアクションに到達している時点で入力内容のバリデーションは完了しています。
        // エラーの場合はエラーメッセージと共に「back()->withInput()」と同等の処理が行われます。
        $validated_data = $request->validated();

        // back()を使用して収支情報一覧画面へ戻ります。
        // これにより表示年月とページのパラメータは保持されたままとなります。
        $renderable = back();

        // DBへの保存に成功すると保存したデータ(Model)が返却されます。
        // 失敗した場合はfalseが返却されます。
        $balance_data = $this->balance_data_repository
                ->createData($request->user(), $validated_data);

        // 処理結果メッセージをビューに渡します。
        if ($balance_data !== false) {
            $renderable->with('message', "データの登録が完了しました。");
            $renderable->with('alert_mode', 'success');
        } else {
            $renderable->with('message', "データの登録に失敗しました。再度実行してください。");
            $renderable->with('alert_mode', 'danger');
        }

        // 成功の場合は連続登録のため、失敗の場合は再試行のために入力データを復元します。
        $renderable->withInput();
        return $renderable;
    }
    /**
     * IDを元にデータの削除を実行します。
     *
     * @param \Illuminate\Http\Request $request
     * @param string $id 削除対象の収支情報のID
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function delete(Request $request, string $id)
    {
        // 削除対象のデータを取得します。
        $balance_data = $this->balance_data_repository
            ->getDataById($request->user(), $id);

        // 削除の成否が返却されます。
        $result = $balance_data->delete();

        // back()を使用して収支情報一覧画面へ戻ります。
        // これにより表示年月とページのパラメータは保持されたままとなります。
        $renderable = back();

        // 処理結果メッセージをビューに渡します。
        // また、入力フォームには再度新規登録できる状態のデータおよびactionを設定します。
        if ($result) {
            $renderable->with('message', "データの削除が完了しました。");
            $renderable->with('alert_mode', 'success');
            unset($balance_data->id);
            $renderable->with('balance_data', $balance_data);
        } else {
            $renderable->with('message', "【ID:{$id}】 の削除に失敗しました。再度実行してください。");
            $renderable->with('alert_mode', 'danger');
        }
        return $renderable;
    }
    /**
     * 収支情報のIDを受け取り、入力フォームを変更モードにするためのアクションです。
     *
     * @param \Illuminate\Http\Request $request
     * @param String $id 変更対象とする収支情報データのIDです。
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function edit(Request $request, string $id)
    {
        // 収支情報のIDに対応するデータを取得します。
        $balance_data = $this->balance_data_repository
            ->getDataById($request->user(), $id);

        // back()を使用して収支情報一覧画面へ戻ります。
        // これにより表示年月とページのパラメータは保持されたままとなります。
        $renderable = back();

        // 収支情報一覧で使用する以下のデータをビューに渡します。
        // 1. 収支情報のIDに対応するデータ
        // 2. 入力フォームのaction属性に設定する「情報変更用」のURLを持つrouter
        $renderable->with('balance_data', $balance_data);
        $renderable->with('form_router', ['balancedata.update', $id]);
        return $renderable;
    }

    /**
     * 入力フォームのデータを受け取り、DBデータを更新するためのアクションです。
     *
     * @param App\Http\Requests\BalanceDataRequest $request
     * バリデーション済みの入力フォームの内容
     * @param string $id 更新対象の収支情報のID
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function update(BalanceDataRequest $request, string $id)
    {
        // このアクションに到達している時点で入力内容のバリデーションは完了しています。
        // エラーの場合はエラーメッセージと共に「back()->withInput()」と同等の処理が行われます。
        $validated_data = $request->validated();

        // back()を使用して収支情報一覧画面へ戻ります。
        // これにより表示年月とページのパラメータは保持されたままとなります。
        $renderable = back();

        // 更新の成否が返却されます。
        $result = $this->balance_data_repository
            ->updateData($request->user(), $id, $validated_data);

        // 処理結果メッセージをビューに渡します。
        // また、入力フォームには再度更新できる状態のデータおよびactionを設定します。
        if ($result) {
            $balance_data = $this->balance_data_repository
                ->getDataById($request->user(), $id);
            $renderable->with('message', "データの更新が完了しました。");
            $renderable->with('alert_mode', 'success');
            $renderable->with('balance_data', $balance_data);
            $renderable->with('form_router', ['balancedata.update', $id]);
        } else {
            $renderable->with('message', "データの更新に失敗しました。再度実行してください。");
            $renderable->with('alert_mode', 'danger');
        }
        return $renderable;
    }
}

resources/views/balancedata/graph.blade.php
<div class="card mt-4">
  <div class="card-header">収支状況グラフ</div>
  <div class="card-body">
    @include('common.ymselect')
    <div id="charts_canvas">
      @if ($lavacharts !== false)
      {!! $lavacharts->render('ComboChart', 'balance_graph', 'charts_canvas'); !!}
      @else
      <div class="alert alert-info mt-3" role="alert">データがありません</div>
      @endif
    </div>
  </div>
</div>

resources/views/balancedata/index.blade.php
{{-- @extends('layouts.app')により、実際にはアプリケーションで共通の部分を持つ --}}
{{-- 「resources/views/layouts/app.blade.php」が最初に読み込まれ、 --}}
{{-- その中の@yield('content')によりこのファイルの中身が読み込まれます。 --}}
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      @include('balancedata.input')
      @include('balancedata.list')
    </div>
  </div>
</div>
@endsection

resources/views/balancedata/input.blade.php
@if (session('message'))
<div class="alert alert-{{ session('alert_mode') }}">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  {!! nl2br(htmlspecialchars(session('message'))) !!}
</div>
@endif
<div class="card">
  <div class="card-header">収支情報編集フォーム</div>
  <div class="card-body">
    {{ Form::model(session('balance_data') ?? $balance_data,[
                'route' => session('form_router') ?? $form_router])}}
    <div class="form-row">
      <div class="mb-3 col-4 col-sm-4 col-md-4 col-lg-2 col-xl-2">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">ＩＤ</span>
          </div>
          {{ Form::text('id', null, [
                            'class' => 'form-control text-center','readonly']) }}
        </div>
      </div>
      <div class="mb-3 col-8 col-sm-8 col-md-8 col-lg-4 col-xl-4">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">日付</span>
          </div>
          {{ Form::date('occurred_at', null, [
                            'class' => 'form-control text-center rounded-right'
                            . ($errors->has('occurred_at') ? ' is-invalid' : ''),
                            'required']) }}
          @if ($errors->has('occurred_at'))
          <div class="invalid-feedback">
            <strong>{{ $errors->first('occurred_at') }}</strong>
          </div>
          @else
          <div class="invalid-feedback">
            <strong>日付は必ず指定してください。</strong>
          </div>
          @endif
        </div>
      </div>

      <div class="mb-3 col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">金額</span>
          </div>
          {{ Form::select('type', ['収入' => '収入', '支出' => '支出'], null, [
                            'class' => 'form-control'
                            . ($errors->has('type') ? ' is-invalid' : '')]) }}
          {{ Form::text('amount', null, [
                            'class' => 'form-control text-right'
                            . ($errors->has('amount') ? ' is-invalid' : ''),
                            'required', 'pattern' => '\d{1,8}']) }}
          <div class="input-group-append">
            <span class="input-group-text rounded-right">円</span>
          </div>
          @if ($errors->has('type') || $errors->has('amount'))
          <div class="invalid-feedback">
            <strong>{{ $errors->first('type') }}</strong>
            <strong>{{ $errors->first('amount') }}</strong>
          </div>
          @else
          <div class="invalid-feedback">
            <strong>金額は1桁から8桁の間で指定してください。</strong>
          </div>
          @endif
        </div>
      </div>

      <div class="mb-3 col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">タイトル</span>
          </div>
          {{ Form::text('title', null, [
                            'class' => 'form-control rounded-right'
                            . ($errors->has('title') ? ' is-invalid' : ''),
                            'required','pattern' => '{1,20}']) }}
          @if ($errors->has('title'))
          <div class="invalid-feedback">
            <strong>{{ $errors->first('title') }}</strong>
          </div>
          @else
          <div class="invalid-feedback">
            <strong>タイトルは必ず指定してください。</strong>
          </div>
          @endif
        </div>
      </div>

      <div class="mb-3 col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">メモ</span>
          </div>
          {{ Form::textarea('description', null, [
                            'class' => 'form-control', 'rows' => 3]) }}
        </div>
      </div>
    </div>
    <div class="text-right">
      {{ Form::button('クリア', [
                    'class' => 'btn btn-outline-danger',
                    'onclick' => 'location.reload();']) }}
      {{ Form::submit('送信', ['class' => 'btn btn-outline-success',
                    'onclick' => 'return balance_data_controller.form_validation(this.form);']) }}
    </div>
    {{ Form::close() }}
  </div>
</div>

resources/views/balancedata/list.blade.php
<div class="card mt-4">
  <div class="card-header">収支情報一覧</div>
  <div class="card-body">
    @include('common.ymselect')
    @if (count($balance_data_list) > 0)
    {{ $balance_data_list->appends(['ym'=>$ym])->links() }}
    <table class="table table-sm table-bordered table-hover">
      <thead class="thead-light">
        <tr>
          <th class="text-center">ＩＤ</th>
          <th class="text-center">日付</th>
          <th class="text-center">区分</th>
          <th class="text-center">金額</th>
          <th class="text-center">タイトル</th>
          <th class="text-center">メモ</th>
          <th class="text-center">操作</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($balance_data_list as $row)
        <tr>
          <td class="text-center">
            <div>{{ $row->id }}</div>
          </td>
          <td class="text-center">
            <div>{{ $row->occurred_at_f }}</div>
          </td>
          <td class="text-center">
            <div>{{ $row->type }}</div>
          </td>
          <td class="text-right">
            <div class="font-weight-bold
                                {{ ($row->type == '収入') ? 'text-success' : 'text-danger' }}">
              {{ $row->amount_f }}
            </div>
          </td>
          <td class="text-center">
            <div>{{ $row->title }}</div>
          </td>
          <td>
            <div>{!! nl2br(htmlspecialchars($row->description)) !!}</div>
          </td>
          <td class="text-center">
            {!! Form::CustomButton('danger', 'delete_data', '削除', $row->id) !!}
            {!! Form::CustomButton('success', 'edit_data', '変更', $row->id) !!}
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    @else
    <div class="alert alert-info mt-3" role="alert">データがありません</div>
    @endif
  </div>
</div>