routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::redirect('/', '/home');
Route::get('/home', 'HomeController@index')->name('home');
Route::prefix('balancedata')->name('balancedata.')->group(function () {
    Route::get('/', 'BalanceDataController@index')->name('index'); // (1)
    Route::post('/create', 'BalanceDataController@create')->name('create'); // (2)
    Route::get('/edit/{id}', 'BalanceDataController@edit')->name('edit'); // (3)
    Route::post('/update/{id}', 'BalanceDataController@update')->name('update'); // (4)
    Route::get('/delete/{id}', 'BalanceDataController@delete')->name('delete'); // (5)
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <div class="card">
                <div class="card-header">{{__('Dashboard')}}</div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif

                    <!-- You are logged in! -->
                    {{ Auth::user()->name }}さん、こんにちは！
                    <br>
                    <!-- <a href="./balancedata">収支情報編集画面を開く</a> -->
                    {{ link_to_route('balancedata.index', '収支情報編集画面を開く') }}
                </div>
            </div>
            @include('balancedata.graph')
        </div>
    </div>
</div>
@endsection